config/routes.rb
Rails.application.routes.draw do
  resources :entries

  resources :users
  resource :login, :only => [:new, :create, :destroy]

  root 'entries#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password

  has_many :entries

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    current_user
  end

  def authenticate
    current_user_id = session[:current_user_id]
    unless current_user_id
      redirect_to new_login_path, notice: "You must be logged in to see that."
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  # before_action :ensure_user_owns_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = current_user.entries
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = current_user.entries.find(params[:id])
    end
    def ensure_user_owns_entry
      if @entry.user != current_user
        render nothing: true, status: :not_found
        # redirect_to root_path, flash: {alert: "You tried to access an entry that doesn't belong to you."}
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.id
      redirect_to root_path, notice: "You have successfully logged in."
    else
      flash.now[:error] = "Your email or password was incorrect."
      render :new
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to new_login_path, notice: "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/new
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_alert(type = :notice)
    if flash[type]
      content_tag(:div, "data-alert" => "data-alert", :class => "alert-box #{type}") do
        flash[type]
      end
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.body %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @entry.body %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Diary" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Diary", root_url %></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <% if logged_in? %>
            <li><%= link_to "Logged in as #{current_user}", "#" %></li>
            <li><%= link_to "Logout", login_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_login_path %></li>
          <% end %>
        </ul>

        <!-- Left Nav Section -->
        <ul class="left">
        </ul>
      </section>
    </nav>
    <%= display_alert(:notice) %>
    <%= display_alert(:alert) %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="row">
  <h1 class="large-12 columns">Login</h1>

  <%= form_tag login_path, :method => :post do %>
    <div class="large-6 columns">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </div>
    <div class="large-6 columns">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <div class="large-12 columns">
      <%= button_tag "Login", :class => "small radius" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
  <h1 class="large-12 columns">Sign up</h1>
  <%= simple_form_for @user do |form| %>
    <div class="large-12 columns">
      <%= form.input :name %>
    </div>
    <div class="large-12 columns">
      <%= form.input :email %>
    </div>
    <div class="large-6 columns">
      <%= form.input :password %>
    </div>
    <div class="large-6 columns">
      <%= form.input :password_confirmation %>
    </div>
    <div class="large-12 columns">
      <%= form.button :submit, class: "radius small" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>